# Generated by Django 3.2 on 2023-02-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('upcomming_billing', 'Upcoming Billing'), ('overdue_billing', 'Overdue Billing'), ('settled_billing', 'Settled Billing'), ('pending_billing', 'Pending Billing')], max_length=50),
        ),
    ]
