# Generated by Django 3.2 on 2023-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('settled', 'Settled'), ('partial', 'Partial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subproperty',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
