# Generated by Django 3.2 on 2023-02-02 11:18

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20230202_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50)),
                ('name_lc', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('secondary_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, default='customers/nopp.jpg', null=True, upload_to=master.models.customer_image_upload_to)),
                ('id_no', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.district')),
                ('local_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.locallevel')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.province')),
            ],
            options={
                'db_table': 'mst_agent',
            },
        ),
    ]
