# Generated by Django 3.2 on 2023-02-03 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.property'),
        ),
    ]
